### ISSUE TITLE
Unable to start the node server.

### ISSUE THREAD

**Issue by hyunlee1o** [pwambach/ethereum-visualization#4]
I am using node v6.13.1.
When I follow the instructions to start the server
`npm i
API_KEY=XYZ node server/server.js`
All that i get is 
`
async function updateBlocks() {                                                                                                                                                     
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jorge/ethereum-visualization/server/server.js:4:41)
`
I am unable to work therefore and i'm really interested in trying this sofware in a private network.
Thanks in advance.

**Comment by pwambach** [comment]
Sorry for the late answer. The node server requires support for async/await which is available in node v 8+

**Comment by hyunlee1o** [comment]
np, i updated to node8
and everything is fine, thanks
